# Generated by rust2rpm 23
%bcond_without check

%global crate joshuto

Name:           rust-joshuto
Version:        0.9.7
Release:        1%?dist
Summary:        Terminal file manager inspired by ranger

License:        LGPL-3.0
URL:            https://crates.io/crates/joshuto
Source:         %{crates_source}

BuildRequires:  anda-srpm-macros rust-packaging >= 21

%global _description %{expand:
Terminal file manager inspired by ranger.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/joshuto

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep_online

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
