# Generated by rust2rpm 27
%bcond check 0

Name:           pbpctrl
Version:        0.1.8
Release:        %autorelease
Summary:        Command-line utility for controlling Google Pixel Buds Pro

SourceLicense:  MIT OR Apache-2.0
License:        (0BSD OR MIT OR Apache-2.0) AND Apache-2.0 AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND BSD-2-Clause AND (BSD-3-Clause OR MIT OR Apache-2.0) AND MIT AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR LGPL-2.1-or-later) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/qzed/pbpctrl
Source:         %url/archive/refs/tags/v%version.tar.gz
Packager:       madonuko <mado@fyralabs.com>

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel

%global _description %{expand:
Command-line utility for controlling Google Pixel Buds Pro.}

%description %{_description}

%prep
%autosetup -n pbpctrl-%{version} -p1
%cargo_prep_online

%build
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies
%{cargo_build} -p pbpctrl

%install
install -Dm755 target/rpm/pbpctrl -t %buildroot%_bindir

%files
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%{_bindir}/pbpctrl
