# Generated by rust2rpm 23
%bcond_without check

%global crate detox

Name:           rust-detox
Version:        0.1.2
Release:        %autorelease
Summary:        Quickly clean up your development directories on disk

License:        MIT
URL:            https://crates.io/crates/detox
Source:         %{crates_source}

BuildRequires:  anda-srpm-macros rust-packaging >= 21

%global _description %{expand:
Quickly clean up your development directories on disk.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/detox

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep_online

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
