# Generated by rust2rpm 27
%global crate matugen

Name:           rust-matugen
Version:        4.0.0
Release:        1%?dist
Summary:        Material you color generation tool with templates

License:        GPL-2.0-or-later
URL:            https://crates.io/crates/matugen
Source:         %{crates_source}
Source1:        https://raw.githubusercontent.com/InioX/matugen/refs/tags/v%version/README.md
Source2:        https://raw.githubusercontent.com/InioX/matugen/refs/tags/v%version/CHANGELOG.md
Source3:        https://raw.githubusercontent.com/InioX/matugen/refs/tags/v%version/LICENSE

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  anda-srpm-macros
BuildRequires:  mold

Packager:       sadlerm <sad_lerm@hotmail.com>

%global _description %{expand:
A material you color generation tool with templates.}

%description %{_description}


%package     -n %{crate}
Summary:        %{summary}
License:        GPL-2.0-or-later
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/matugen

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online
install -Dpm0644 -t . %{S:1} %{S:2} %{S:3}

%build
%{cargo_license_online} > LICENSE.dependencies

%install
%cargo_install

%changelog
* Wed Jan 22 2025 sadlerm <sad_lerm@hotmail.com> - 2.4.1-1
- Initial package
