# Generated by rust2rpm 27
%global crate matugen

Name:           rust-matugen
Version:        4.0.0
Release:        1%?dist
Summary:        Material you color generation tool with templates

License:        GPL-2.0
URL:            https://crates.io/crates/matugen
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  anda-srpm-macros
BuildRequires:  mold

Packager:       sadlerm <sad_lerm@hotmail.com>

%global _description %{expand:
A material you color generation tool with templates.}

%description %{_description}


%package     -n %{crate}
Summary:        %{summary}
License:        GPL-2.0
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/matugen


%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/


%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online

%build
%{cargo_license_summary_online}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%changelog
* Wed Jan 22 2025 sadlerm <sad_lerm@hotmail.com> - 2.4.1-1
- Initial package
