# Generated by go2rpm 1.19.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/daeuniverse/dae
%global goipath         github.com/daeuniverse/dae
Version:                2.0.0

%gometa -f

%global common_description %{expand:
EBPF-based Linux high-performance transparent proxy solution.}

%global golicenses      LICENSE
%global godocs          docs .markdownlint-cli2.jsonc CHANGELOGS.md README.md\\\
                        hack/templates/example-config.md

Name:           dae
Release:        1%?dist
Summary:        EBPF-based Linux high-performance transparent proxy solution

License:        AGPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}
Packager:       madonuko <mado@fyralabs.com>
BuildRequires:  clang

%description %{common_description}

%gopkg

%prep
%git_clone
%goprep_online -Ae

%if %{without bootstrap}
%build
%define gomodulesmode GO111MODULE=on
cat<<EOF > edit.sed
s@go build@%{?gobuilddir:GOPATH="%{gobuilddir}:${GOPATH:+${GOPATH}:}%{?gopath}"} %{?gomodulesmode} go build %{gobuildflags}@g
/^BUILD_ARGS/{s@-s -w@@g; s@-trimpath@@g}
EOF
sed -f edit.sed -i Makefile
%make_build VERSION="%version" NOSTRIP="y" OUTPUT="%{gobuilddir}/bin/dae"
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs .markdownlint-cli2.jsonc CHANGELOGS.md README.md
%doc hack/templates/example-config.md
%{_bindir}/dae
%endif

%gopkgfiles

%changelog
* Mon Jun 15 2026 madonuko <mado@fyralabs.com> - 1.1.0-1
- Initial package.
