# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/charmbracelet/glow
%global goipath         github.com/charmbracelet/glow
Version:                1.5.1

gometa -f


%global common_description %{expand:
Render markdown on the CLI, with pizzazz! 💅🏻.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Render markdown on the CLI, with pizzazz! 💅🏻

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/glow %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
