# generated by cabal-rpm-2.3.2
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global pkg_name kleene
%global pkgver %{pkg_name}-%{version}
%{?haskell_setup}

# testsuite missing deps: tasty-hunit tasty-quickcheck

Name:           ghc-%{pkg_name}
Version:        0.2
Release:        1%{?dist}
Summary:        Kleene algebra

License:        BSD-3-Clause
URL:            https://hackage.haskell.org/package/kleene
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-MemoTrie-devel
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-lattices-devel
BuildRequires:  ghc-range-set-list-devel
BuildRequires:  ghc-regex-applicative-devel
BuildRequires:  ghc-semigroupoids-devel
BuildRequires:  ghc-step-function-devel
%if %{with ghc_prof}
BuildRequires:  ghc-MemoTrie-prof
BuildRequires:  ghc-QuickCheck-prof
BuildRequires:  ghc-base-prof
BuildRequires:  ghc-bytestring-prof
BuildRequires:  ghc-containers-prof
BuildRequires:  ghc-lattices-prof
BuildRequires:  ghc-range-set-list-prof
BuildRequires:  ghc-regex-applicative-prof
BuildRequires:  ghc-semigroupoids-prof
BuildRequires:  ghc-step-function-prof
%endif
# End cabal-rpm deps

Packager:       Owen Zimmerman <owen@fyralabs.com>

%description
Kleene algebra

Think: Regular expressions

Implements ideas from /Regular-expression derivatives re-examined/ by Scott
Owens, John Reppy and Aaron Turon <https://doi.org/10.1017/S0956796808007090>.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-static%{?_isa} = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%if %{with haddock}
%package doc
Summary:        Haskell %{pkg_name} library documentation
BuildArch:      noarch
Requires:       ghc-filesystem

%description doc
This package provides the Haskell %{pkg_name} library documentation.
%endif


%if %{with ghc_prof}
%package prof
Summary:        Haskell %{pkg_name} profiling library
Requires:       %{name}-devel%{?_isa} = %{version}-%{release}
Supplements:    (%{name}-devel and ghc-prof)

%description prof
This package provides the Haskell %{pkg_name} profiling library.
%endif


%prep
# Begin cabal-rpm setup:
%setup -q -n %{pkgver}
# End cabal-rpm setup
sed -i 's/QuickCheck         >=2\.16\.0\.0/QuickCheck         >=2.14    /' kleene.cabal

%build
# Begin cabal-rpm build:
%ghc_lib_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_lib_install
# End cabal-rpm install


%files -f %{name}.files
# Begin cabal-rpm files:
%license LICENSE
# End cabal-rpm files


%files devel -f %{name}-devel.files
%doc CHANGELOG.md example.png


%if %{with haddock}
%files doc -f %{name}-doc.files
%license LICENSE
%endif


%if %{with ghc_prof}
%files prof -f %{name}-prof.files
%endif


%changelog
* Mon Aug 17 2026 Owen Zimmerman <owen@fyralabs.com> - 0.2-1
- Initial commit
