# Generated by go2rpm 1.16.0
%bcond check 0
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/u-root/u-root
%global goipath         github.com/u-root/u-root
Version:                0.14.0
%global commit          5721ed3ad38a5c889e6c1ed5bbf5242f98a4b591

%gometa -f

%global common_description %{expand:
A fully Go userland with Linux bootloaders! u-root can create a one-binary root
file system (initramfs) containing a busybox-like set of tools written in Go.}

%global golicenses      LICENSE
%global godocs          docs examples AUTHORS CONTRIBUTING.md README.md\\\
                        SECURITY.md roadmap.md tricksandtips.md\\\
                        cmds/exp/esxiboot/README.md cmds/exp/tftpd/README.md\\\
                        cmds/exp/uefiboot/README.md cmds/exp/vmboot/README.md\\\
                        configs/README.md configs/amd64_config.txt\\\
                        configs/arm_config.txt configs/generic_config.txt\\\
                        integration/README.md pkg/boot/systembooter/README.md\\\
                        pkg/netcat/doc.md pkg/netstat/doc.md\\\
                        pkg/smbios/README.md pkg/tc/readme.md\\\
                        tools/golang_patched_dce/README.md tools/tinygo-\\\
                        buildstatus/README.md tools/tinygobb/README.md

Name:           golang-github-u-root
Release:        2%?dist
Summary:        A fully Go userland with Linux bootloaders! u-root can create a one-binary root file system (initramfs) containing a busybox-like set of tools written in Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%build
%define gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/u-root %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs examples AUTHORS CONTRIBUTING.md README.md SECURITY.md roadmap.md
%doc tricksandtips.md
%doc configs/amd64_config.txt configs/arm_config.txt configs/generic_config.txt
%{_bindir}/u-root
%endif

%gopkgfiles

%changelog
%autochangelog
