%global __brp_mangle_shebangs %{nil}

# Generated by rust2rpm 27
%bcond check 1

%global crate gping

Name:           rust-gping
Version:        1.19.0
Release:        2%?dist
Summary:        Ping, but with a graph

License:        MIT
URL:            https://crates.io/crates/gping
Source:         %{crates_source}
Source1:        https://github.com/orf/gping/blob/gping-v%version/LICENSE

BuildRequires:  anda-srpm-macros rust-packaging >= 21 mold

%global _description %{expand:
Ping, but with a graph.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND MIT AND (MIT AND Apache-2.0) AND (MIT OR Apache-2.0) AND Unicode-3.0 AND (Unlicense OR MIT) AND Zlib
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc readme.md
%{_bindir}/gping

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online

%build
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
%cargo_install
cp %{S:1} .

%if %{with check}
%check
%cargo_test
%endif
