# Prebuilt Bun-compiled binary: debuginfo is meaningless and stripping corrupts
# its embedded data (breaks --version / app version), so disable both.
%define debug_package %{nil}
%global __strip /bin/true

%ifarch x86_64
%global a x64-baseline
%elifarch aarch64
%global a arm64
%endif

# Only arches with upstream prebuilt binaries.
ExclusiveArch:  x86_64 aarch64

%global appid ai.opencode.opencode

Name:			opencode
Version:		1.18.9
Release:		1%{?dist}
Summary:		Open source AI coding agent for the terminal, IDE, and desktop
License:		MIT
URL:			https://opencode.ai
Source0:		https://github.com/anomalyco/opencode/releases/download/v%{version}/opencode-linux-%{a}.tar.gz
Source1:		%{appid}.metainfo.xml
Source2:		LICENSE
Packager:		Caio Bruno <cbrunofb@gmail.com>

%description
opencode is an open source AI coding agent that helps you write code in your
terminal, IDE, or desktop. It supports 75+ LLM providers (including local
models), LSP integration, multi-session workflows, GitHub Copilot and ChatGPT
login, and the Model Context Protocol (MCP).

%pkg_completion -Bfz opencode

%prep
%autosetup -C
cp %{SOURCE1} %{SOURCE2} .

%build
# Prebuilt binary, nothing to compile.

%install
# The binary may write to $HOME on startup; give it a writable scratch dir.
export HOME=%{_builddir}/oc-home
mkdir -p "$HOME"

install -Dpm755 opencode -t %{buildroot}%{_bindir}

# Shell completions are generated by the binary itself (like bun-bin).
./opencode completion bash > opencode.bash
./opencode completion zsh  > _opencode
./opencode completion fish > opencode.fish
install -Dm644 opencode.bash %{buildroot}%{bash_completions_dir}/opencode
install -Dm644 _opencode     %{buildroot}%{zsh_completions_dir}/_opencode
install -Dm644 opencode.fish %{buildroot}%{fish_completions_dir}/opencode.fish

%terra_appstream -o %{SOURCE1}

%files
%license LICENSE
%{_bindir}/opencode
%{_metainfodir}/%{appid}.metainfo.xml

%changelog
* Wed Jul 29 2026 Caio Bruno <cbrunofb@gmail.com>
- Initial package
