# Generated by go2rpm 1.19.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/Equicord/Equilotl
%global goipath         github.com/Equicord/Equilotl
Version:                2.2.6

%gometa -f

%global common_description %{expand:
A cross platform gui/cli app for installing Equicord.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           equilotl
Release:        %autorelease
Summary:        A cross platform gui app for installing Equicord

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}
Packager:       madonuko <mado@fyralabs.com>
BuildRequires:  pkg-config libGL-devel libXxf86vm-devel gcc-c++
BuildRequires:  wayland-devel libxkbcommon-devel wayland-protocols-devel extra-cmake-modules
BuildRequires:  libXcursor-devel libXi-devel libXinerama-devel libXrandr-devel
RemovePathPostFixes: .wayland

%description %{common_description}

%package cli
Summary:        A cross platform cli app for installing Equicord
RemovePathPostFixes: .cli
%description cli %{common_description}

%package x11
Summary:        A cross platform gui (X11) app for installing Equicord
RemovePathPostFixes: .x11
%description x11 %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%build
%define gomodulesmode GO111MODULE=on
export GO_BUILDTAGS="wayland"
%gobuild -o %{gobuilddir}/bin/Equilotl.wayland equilotl
export GO_BUILDTAGS=""
%gobuild -o %{gobuilddir}/bin/Equilotl.x11     equilotl
export GO_BUILDTAGS="cli"
%gobuild -o %{gobuilddir}/bin/Equilotl.cli     equilotl
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md
%{_bindir}/Equilotl.wayland

%files cli
%license LICENSE
%doc README.md
%{_bindir}/Equilotl.cli

%files x11
%license LICENSE
%doc README.md
%{_bindir}/Equilotl.x11
%endif

%gopkgfiles

%changelog
* Sat Jun 27 2026 madonuko <mado@fyralabs.com> - 2.2.6-1
- Initial package
