# Generated by rust2rpm 27
%bcond check 0

%global crate xdvdfs-cli

Name:           rust-xdvdfs-cli
Version:        0.8.3
Release:        %autorelease
Summary:        Tool for interacting with XISO/XDVDFS images

License:        MIT
URL:            https://crates.io/crates/xdvdfs-cli
Source:         %{crates_source}
Source1:		https://raw.githubusercontent.com/antangelo/xdvdfs/v%version/LICENSE
Packager:		madonuko <mado@fyralabs.com>

BuildRequires:  anda-srpm-macros
BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Tool for interacting with XISO/XDVDFS images.}

%description %{_description}

%package     -n xdvdfs
Summary:        %{summary}
License:        ((Apache-2.0 OR MIT) AND BSD-3-Clause) AND (Apache-2.0 OR MIT) AND MIT AND (MIT AND BSD-3-Clause) AND (MIT OR Apache-2.0) AND (Unlicense OR MIT) AND Zlib

%description -n xdvdfs %{_description}

%files       -n xdvdfs
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/xdvdfs

%prep
%autosetup -n %{crate}-%{version} -p1
cp %{S:1} LICENSE
%cargo_prep_online

%build
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif
