name: Failing Builds
description: Report missing or out-of-date packages.
title: "[FAILING] "
labels: ["bug"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - hamachitan
type: failing
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        **Please update the issue title with the short package name.**
  - type: input
    id: pkg
    attributes:
      label: Full Raw Package Name (e.g. anda-0.4.14-1.fcrawhide.x86_64)
      description: |
        If you report multiple packages, only the main package is needed if applicable, or separate them with spaces otherwise. Obtain the full package name using `rpm -qa pkg-name`.

        **The format MUST BE LITERALLY THE SAME as `anda-0.4.14-1.fc43.x86_64`. Do NOT add anything else, not even backticks.**
      placeholder: anda-0.4.14-1.fc43.x86_64 (MUST be under this format, no backticks)
    validations:
      required: true
  - type: dropdown
    id: releasever
    attributes:
      label: Release Version
      description: Which version of Terra are you using?
      options:
        - frawhide
        - f45
        - f44
        - f43
        - el10
      default: 1
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details on e.g. what the latest version is supposed to be, the link to the failing CI build, etc.
