# Generated by go2rpm 1.19.0
%bcond check 0
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/ente-io/ente
%global goipath         github.com/ente-io/ente/cli
%global tag             cli-v0.2.3
Version:                %(echo %tag | sed 's/^cli-v//')

%gometa -f

%global common_description %{expand:
The Ente CLI is a Command Line Utility for exporting data from Ente. It also does a few more things, for example, you can use it to decrypt the export from Ente Auth.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md cli/README.md SECURITY.md SUPPORT.md
Name:           ente
Release:        1%?dist
Summary:        💚 End-to-end encrypted cloud for everything
Packager:       madonuko <mado@fyralabs.com>

License:        AGPL-3.0-only
URL:            ente.com
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%build
%global gomodulesmode GO111MODULE=on
cd cli
%gobuild -o %{gobuilddir}/bin/ente .
%endif

%install
cd cli
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md SECURITY.md SUPPORT.md cli/README.md
%{_bindir}/ente
%endif

%gopkgfiles

%changelog
* Tue Jun 16 2026 madonuko <mado@fyralabs.com> - 0.2.3-1
- Initial package.
