# This variable determines what kind of modules get installed on the system
# until the Nvidia driver provides only the open source variant.
#
# The name of the variable is the name of the folder that hosts the kernel
# module code inside the driver installer:
#
# +-------------+---------------------+----------------+
# | Value       | Type                | License type   |
# +-------------+---------------------+----------------+
# | kernel      | Proprietary drivers | NVIDIA license |
# +-------------+---------------------+----------------+
# | kernel-open | Open source drivers | Dual MIT/GPL   |
# +-------------+---------------------+----------------+

# TERRA-SPECIFIC NOTES:
# A script has been added to the spec to detect if a Pascal, Maxwell, or lower card is in use.
# This script will switch to closed modules if one is.
# When NVIDIA drops all support for closed modules, this script will be removed.

MODULE_VARIANT=kernel-open
