# Generated by go2rpm 1.10.0
%bcond_without check

# https://github.com/github/git-sizer
%global goipath         github.com/github/git-sizer
Version:                1.5.0
%global commit          b84ee4d41db733827387690506556739b0c02817

%global common_description %{expand:
Compute various size metrics for a Git repository, flagging those that might
cause problems.}

%global golicenses      LICENSE.md
%global godocs          docs CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

%gometa -f

Name:           golang-github-git-sizer
Release:        %autorelease
Summary:        Compute various size metrics for a Git repository, flagging those that might cause problems

License:        MIT
URL:            %{gourl}
Source:         %{gosource}
BuildRequires:  git-core

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1
go mod download

%build
export GO111MODULE=off
go build -buildmode pie -compiler gc -tags="rpm_crashtraceback ${GO_BUILDTAGS-${BUILDTAGS-}}" -a -v -x -ldflags "${GO_LDFLAGS-${LDFLAGS-}}  -B 0x$(echo "%{name}-%{version}-%{release}-${SOURCE_DATE_EPOCH:-}" | sha1sum |
 cut -d ' ' -f1) -compressdwarf=false -linkmode=external -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1'" -o git-sizer .

# -linkmode=external -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1   '

%install
install -m 0755 -vd           %{buildroot}%{_bindir}
install -m 0755 -vp git-sizer %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc docs CODE_OF_CONDUCT.md CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
