# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/rs/curlie
%global goipath         github.com/rs/curlie
Version:                1.7.1

%gometa -f

%global common_description %{expand:
The power of curl, the ease of use of httpie.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The power of curl, the ease of use of httpie

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

Requires:       curl

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/curlie %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%doc README.md
%license LICENSE
%doc README.md
%{_bindir}/curlie

%gopkgfiles

%changelog
%autochangelog

%package -n curlie
Requires:       curl
Summary:        The power of curl, the ease of use of httpie
%description -n curlie %{common_description}
%files -n curlie
%license LICENSE
%{_bindir}/curlie
