# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/xyproto/env
%global goipath         github.com/xyproto/env
Version:                2.4.0

%gometa -f

%global common_description %{expand:
Provide default values when fetching environment variables.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-%{goname}
Release:        1%?dist
Summary:        Provide default values when fetching environment variables

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
