# Generated by rust2rpm 23
%bcond_without check

%global crate game-2048

Name:           rust-game-2048
Version:        0.5.1
Release:        %autorelease
Summary:        Cli implementation of the popular 2048 game writen in rust

License:        MIT
URL:            https://crates.io/crates/game-2048
Source:         %{crates_source}

BuildRequires:  anda-srpm-macros rust-packaging >= 21

%global _description %{expand:
Cli implementation of the popular 2048 game writen in rust.}

%description %{_description}

%package     -n 2048-rs
Summary:        %{summary}

%description -n 2048-rs %{_description}

%files       -n 2048-rs
%doc README.md
%{_bindir}/2048-rs

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep_online

%build
%cargo_build

%install
%cargo_install
install -Dm755 %{buildroot}/%{_bindir}/game-2048 %{buildroot}/%{_bindir}/2048-rs
rm %{buildroot}/%{_bindir}/game-2048

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
