Name:			gtk4-layer-shell
Version:		1.0.0
Release:		1%?dist
Summary:		Library to build desktop components using Layer Shell Wayland protocol and GTK4
License:		MIT
URL:			https://github.com/wmww/gtk4-layer-shell
Source0:		%url/archive/refs/tags/v%version.tar.gz
BuildRequires:	meson ninja-build python3.11 vala
BuildRequires:	libwayland-client gtk4-devel gobject-introspection gtk-doc

%description
A library for using the Layer Shell Wayland protocol with GTK4. With this
library you can build desktop shell components such as panels, notifications
and wallpapers. You can use it to anchor your windows to a corner or edge of
the output, or stretch them across the entire output. This Library is
compatible with C, C++ and any language that supports GObject introspection
files (Python, Vala, etc).


%package doc
Summary: gtk4-layer-shell documentation generated by gtk-doc

%description doc
%summary.


%package vapi
Summary: gtk4-layer-shell vapi data

%description vapi
%summary.


%prep
%autosetup

%build
%meson -Ddocs=true
%meson_build

%install
%meson_install


%files
%doc README.md
%license LICENSE
/usr/include/gtk4-layer-shell/gtk4-layer-shell.h
/usr/lib64/girepository-1.0/Gtk4LayerShell-1.0.typelib
/usr/lib64/libgtk4-layer-shell.so*
/usr/lib64/pkgconfig/gtk4-layer-shell-0.pc
/usr/share/gir-1.0/Gtk4LayerShell-1.0.gir

%files doc
/usr/share/gtk-doc/html/gtk-layer-shell

%files vapi
/usr/share/vala/vapi/gtk4-layer-shell-0.deps
/usr/share/vala/vapi/gtk4-layer-shell-0.vapi


%changelog
* Fri Apr 28 2023 windowsboy111 <windowsboy111@fyralabs.com>
- Initial package.
