# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/dhth/prs
%global goipath         github.com/dhth/prs
Version:                1.0.0

%gometa -f

%global common_description %{expand:
Stay updated on PRs from your terminal.}

%global golicenses      LICENSE
%global godocs          README.md ui/assets/help.md

Name:           golang-github-dhth-prs
Release:        %autorelease
Summary:        Stay updated on PRs from your terminal

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  anda-srpm-macros

Packager:       sadlerm <lerm@chromebooks.lol>

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%build
%gobuild -o %{gobuilddir}/bin/prs %{goipath}

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md ui/assets/help.md
%{_bindir}/prs
%endif

%gopkgfiles

%changelog
* Sun Feb  9 2025 sadlerm <lerm@chromebooks.lol>
- Initial package
