# Generated by rust2rpm 23
%define debug_package %{nil}
%global crate zoxide

Name:           rust-zoxide
Version:        0.9.1
Release:        1%{?dist}
Summary:        Smarter cd command for your terminal

License:        MIT
URL:            https://crates.io/crates/zoxide
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          zoxide-fix-metadata-auto.diff

BuildRequires:  anda-srpm-macros rust-packaging >= 21

%global _description %{expand:
Smarter cd command for your terminal.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%{_bindir}/zoxide

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep_online

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
