# Generated by rust2rpm 26
#bcond_without check
%bcond_without mold

%global crate bandwhich

Name:           rust-bandwhich
Version:        0.23.0
Release:        1%?dist
Summary:        Display current network utilization by process, connection and remote IP/hostname

License:        MIT
URL:            https://crates.io/crates/bandwhich
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          bandwhich-fix-metadata-auto.diff

BuildRequires:  anda-srpm-macros mold cargo-rpm-macros >= 24

%global _description %{expand:
Display current network utilization by process, connection and remote
IP/hostname.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        MIT

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc INSTALL.md
%doc README.md
%{_bindir}/bandwhich

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online

%build
#cargo_build
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
