# generated by cabal-rpm-2.3.2
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global pkg_name arduino-copilot
%global pkgver %{pkg_name}-%{version}
%{?haskell_setup}

# testsuite missing deps: temporary

Name:           ghc-%{pkg_name}
Version:        1.7.9
Release:        1%{?dist}
Summary:        Arduino programming in haskell using the Copilot stream DSL

License:        BSD-3-Clause
URL:            https://hackage.haskell.org/package/arduino-copilot
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-copilot-devel
BuildRequires:  ghc-copilot-c99-devel
BuildRequires:  ghc-copilot-language-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-sketch-frp-copilot-devel
BuildRequires:  ghc-temporary-devel
%if %{with ghc_prof}
BuildRequires:  ghc-base-prof
BuildRequires:  ghc-containers-prof
BuildRequires:  ghc-copilot-prof
BuildRequires:  ghc-copilot-c99-prof
BuildRequires:  ghc-copilot-language-prof
BuildRequires:  ghc-directory-prof
BuildRequires:  ghc-filepath-prof
BuildRequires:  ghc-mtl-prof
BuildRequires:  ghc-optparse-applicative-prof
BuildRequires:  ghc-sketch-frp-copilot-prof
BuildRequires:  ghc-temporary-prof
%endif
# End cabal-rpm deps

Packager:       Owen Zimmerman <owen@fyralabs.com>

%description
Arduino-copilot contains the basic building blocks to program your Arduino
Nano, Arduino Uno or compatible hardware using Haskell and Functional Reactive
Programming (FRP).

arduino-copilot uses the Copilot stream DSL (domain-specific language) to
generate an Arduino sketch, which can be loaded in the Arduino IDE and uploaded
to the board. Other methods of deploying sketches to the Arduino, such as the
Arduino-Makefile, can also be used with a sketch generated by arduino-copilot.

All the messy details are abstracted away, letting you focus on the desired
behavior of the Arduino.

Copilot is a stream (i.e., infinite lists) domain-specific language (DSL) in
Haskell that compiles into embedded C. Copilot contains an interpreter,
multiple back-end compilers, and other verification tools.
<https://copilot-language.github.io/>.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-static%{?_isa} = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development
files.


%if %{with haddock}
%package doc
Summary:        Haskell %{pkg_name} library documentation
BuildArch:      noarch
Requires:       ghc-filesystem

%description doc
This package provides the Haskell %{pkg_name} library documentation.
%endif


%if %{with ghc_prof}
%package prof
Summary:        Haskell %{pkg_name} profiling library
Requires:       %{name}-devel%{?_isa} = %{version}-%{release}
Supplements:    (%{name}-devel and ghc-prof)

%description prof
This package provides the Haskell %{pkg_name} profiling library.
%endif


%prep
# Begin cabal-rpm setup:
%setup -q -n %{pkgver}
# End cabal-rpm setup
sed -i \
    -e 's/copilot (== 4\.3\.\*)/copilot (== 4.5.*)/' \
    -e 's/copilot-c99 (== 4\.3\.\*)/copilot-c99 (== 4.5.*)/' \
    -e 's/copilot-language (== 4\.3\.\*)/copilot-language (== 4.5.*)/' \
    %{pkg_name}.cabal

%build
# Begin cabal-rpm build:
%ghc_lib_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_lib_install
# End cabal-rpm install


%files -f %{name}.files
# Begin cabal-rpm files:
%license LICENSE
# End cabal-rpm files


%files devel -f %{name}-devel.files
%doc CHANGELOG Examples README TODO


%if %{with haddock}
%files doc -f %{name}-doc.files
%license LICENSE
%endif


%if %{with ghc_prof}
%files prof -f %{name}-prof.files
%endif


%changelog
* Mon Jul 20 2026 Owen Zimmerman <owen@fyralabs.com> - 1.7.9-1
- Initial commit
