# Generated by rust2rpm 23
%bcond_without check

%global crate umu-wrapper

Name:           rust-umu-wrapper
Version:        0.2.0
Release:        %autorelease
Summary:        Simplified wrapper for UMU-Launcher

License:        MIT
URL:            https://crates.io/crates/umu-wrapper
Source:         %{crates_source}

BuildRequires:  mold anda-srpm-macros rust-packaging >= 21

%global _description %{expand:
Simplified wrapper for UMU-Launcher.}

%description %{_description}

%package     -n umu-wrapper
Summary:        %{summary}

%description -n umu-wrapper %{_description}

%files       -n umu-wrapper
%doc README.md
%{_bindir}/umu-wrapper

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep_online

%build
%cargo_build

%install
%cargo_install


%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
