# Generated by go2rpm 1.9.0
%bcond_with check

%global debug_package %{nil}

# https://github.com/FyshOS/fynedesk
%global goipath         github.com/FyshOS/fynedesk
Version:                0.3.0

%gometa -f


%global common_description %{expand:
A full desktop environment for Linux/Unix using Fyne.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md CHANGELOG.md

Name:           %{goname}
Release:        %autorelease
Summary:        A full desktop environment for Linux/Unix using Fyne

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

Requires: arandr
Requires: xbacklight
Requires: network-manager-applet
BuildRequires: make

%prep
%goprep
%autopatch -p1

%generate_buildrequires
#%%go_generate_buildrequires

%build
%make_build

%install
%gopkginstall
install -m 0755 -vd %{buildroot}%{_bindir}
%make_install

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS README.md CHANGELOG.md
%{_bindir}/*
%{_datadir}/xsessions/fynedesk.desktop

%gopkgfiles

%changelog
%autochangelog
