# Generated by go2rpm 1.9.0
%bcond_with check

%global debug_package %{nil}

# https://github.com/FyshOS/fynedesk
%global goipath         github.com/FyshOS/fynedesk
Version:                0.3.0

%gometa -f


%global common_description %{expand:
A full desktop environment for Linux/Unix using Fyne.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md CHANGELOG.md

Name:           %{goname}
Release:        %autorelease
Summary:        A full desktop environment for Linux/Unix using Fyne

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}
BuildRequires:  git
BuildRequires:  libX11-devel
BuildRequires:  libXcursor-devel
BuildRequires:  libXi-devel
BuildRequires:  libXinerama-devel
BuildRequires:  libXrandr-devel
BuildRequires:  xorg-x11-server-devel
BuildRequires:  libXxf86vm-devel
BuildRequires:  pkgconfig(gl)

Requires: arandr
Requires: xbacklight
Requires: network-manager-applet
BuildRequires: make
BuildRequires: golang

%description %{common_description}

%gopkg


%prep
%goprep
%autopatch -p1

%generate_buildrequires

%build
CGO_ENABLED=0
GOOS=linux
%ifarch x86_64
GOARCH=amd64
%elifarch aarch64
GOARCH=arm64
%endif
go build -ldflags '-linkmode external -s -w -extldflags "--static-pie"' -buildmode=pie -tags 'osusergo,netgo,static_build' ./cmd/fynedesk_runner
go build -ldflags '-linkmode external -s -w -extldflags "--static-pie"' -buildmode=pie -tags 'osusergo,netgo,static_build' ./cmd/fynedesk

%install
%gopkginstall
install -m 0755 -vd %{buildroot}%{_bindir}
%make_install
rm %buildroot%_datadir/gocode/src/github.com/FyshOS/fynedesk/{CHANGELOG.md,README.md,.goipath}

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS README.md CHANGELOG.md
%ghost %_datadir/gocode/src/github.com/FyshOS/fynedesk/{CHANGELOG.md,README.md,.goipath}
%{_bindir}/*
%{_datadir}/xsessions/fynedesk.desktop

%gopkgfiles

%changelog
%autochangelog
