# Generated by rust2rpm 28
%bcond check 1

%global crate dysk

Name:           rust-dysk
Version:        3.6.0
Release:        1%?dist
Summary:        Give information on mounted filesystems

License:        MIT
URL:            https://crates.io/crates/dysk
Source:         %{crates_source}
Packager:       madonuko <mado@fyralabs.com>

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Give information on mounted filesystems.}

%description %{_description}

%package     -n %{crate}
URL:            https://dystroy.org/dysk
Summary:        %{summary}
License:        (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR MIT OR Apache-2.0) AND MIT AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/dysk

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online

%build
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Mar 05 2026 madonuko <mado@fyralabs.com> - 3.6.0-1
- Initial package.
