%{?python_enable_dependency_generator}

%global __arch_install_post /bin/true
%global _sbindir /usr/sbin

# Rakuos's fork hit a debuginfo Name collision with apparmor-libs32.spec
# on EL10 CI. Fedora branches build fine with debuginfo enabled, so only
# disable it there.
%if 0%{?rhel}
%global debug_package %{nil}
%endif

%bcond_with tests

Name:           apparmor
Version:        6.0.0~alpha1
Release:        1%{?dist}
Summary:        AppArmor userspace components

%define baseversion %(echo %{version} | cut -d. -f-2)
%global normver %(echo %version | sed 's/~/-/')

License:        GPL-2.0-only
URL:            https://gitlab.com/apparmor/apparmor
Source0:        %url/-/archive/v%normver/apparmor-v%normver.tar.gz
Source1:        apparmor.preset
Patch01:        0001-fix-avahi-daemon-authselect-denial-in-fedora.patch
Patch02:        0001-fix-denial-on-dnsmask-for-nsswitch.patch
Patch03:        0001-fix-apparmor-waydroid-denials.patch
Patch04:        0001-fix-swig-new_copy_array-removed-in-swig-4.5.0.patch

BuildRequires:  gcc
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  gcc-c++
BuildRequires:  libstdc++-static
BuildRequires:  flex
BuildRequires:  bison
BuildRequires:  swig
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  %{_bindir}/podchecker
BuildRequires:  %{_bindir}/pod2html
BuildRequires:  gettext
BuildRequires:  pam-devel
BuildRequires:  httpd-devel
BuildRequires:  systemd-rpm-macros
BuildRequires:  autoconf-archive
BuildRequires:  gawk
BuildRequires:  which
BuildRequires:  libzstd-devel
%if %{with tests}
BuildRequires:  %{_bindir}/runtest
BuildRequires:  %{_bindir}/prove
BuildRequires:  perl(Locale::gettext)
BuildRequires:  perl(Test::More)
%endif

Provides:       %{name}-profiles = %{version}-%{release}
Requires:       %{name}-parser
Recommends:     %{name}-utils
%{?systemd_requires}

%description
AppArmor protects systems from insecure or untrusted processes by running
them in restricted confinement, while still allowing processes to share files,
exercise privilege and communicate with other processes. AppArmor is a Mandatory
Access Control (MAC) mechanism which uses the Linux Security Module (LSM)
framework. The confinement's restrictions are mandatory and are not bound to
identity, group membership, or object ownership. The protections provided are in
addition to the kernel's regular access control mechanisms (including DAC) and
can be used to restrict the superuser.

%package      libs
Summary:      AppArmor library

%description  libs
This package contains the shared library used for making use of the AppArmor
profile and changehat functionality, as well as common log parsing routines.

%package       devel
Summary:       AppArmor development libraries and header files
Requires:      %{name}-libs%{?_isa} = %{version}-%{release}

%description    devel
This package contains AppArmor development libraries and header files.

%package -n     python3-apparmor
Summary:        AppArmor Python3 utility library
Requires:       python3-LibAppArmor = %{version}-%{release}
BuildArch:      noarch

%description -n python3-apparmor
This package provides the python interface to AppArmor. It is used for python
applications interfacing with AppArmor.

%package -n     python3-LibAppArmor
Summary:        AppArmor library Python3 bindings
Requires:       %{name}-libs%{?_isa} = %{version}-%{release}

%description -n python3-LibAppArmor
This package contains Python3 module that contains the language bindings for 
the AppArmor library, libapparmor, which were autogenerated via SWIG.

%package        profiles
Summary:        AppArmor profiles
Provides:       apparmor-profiles = %{version}-%{release}
BuildArch:      noarch

%description    profiles
This package contains default AppArmor profiles.

%package        parser
Summary:        AppArmor userlevel parser utility
Requires:       python3-apparmor = %{version}
# Let it be the AppArmor metapackage
Provides:       %{name} = %{version}-%{release}
Requires:       %{name}-profiles = %{version}-%{release}
Recommends:     %{name}-utils

%description    parser
The AppArmor Parser is a userlevel program that is used to load in
program profiles to the AppArmor Security kernel module.

%package        utils
Summary:        AppArmor User-Level Utilities
Requires:       python3-apparmor = %{version}
Requires:       python3-notify2
Requires:       %{name}-parser

%description    utils
This package provides the aa-logprof, aa-genprof, aa-autodep,
aa-enforce, and aa-complain tools to assist with profile authoring.
Besides it provides the aa-unconfined server information tool.

%package -n     pam_apparmor
Summary:        PAM module for AppArmor change_hat
Requires:       %{name}-libs%{?_isa} = %{version}-%{release}
Requires:       pam%{?_isa}
 
%description -n pam_apparmor
This package provides the PAM module needed to declare various differing
confinement policies when starting PAM sessions by using the changehat 
abilities exposed through libapparmor.

%package -n     mod_apparmor
Summary:        AppArmor module for apache2
Requires:       %{name}-libs%{?_isa} = %{version}-%{release}
Requires:       httpd%{?_isa}

%description -n mod_apparmor
This package provides the Apache module needed to declare various differing
confinement policies when running virtual hosts in the webserver by using the
changehat abilities exposed through libapparmor.

%prep
%autosetup -p1 -n %name-v%normver

%conf
sed -i 's/@VERSION@/%normver/g' libraries/libapparmor/swig/python/setup.py.in
sed -i 's/${VERSION}/%normver/g' utils/Makefile

export PYTHON=%{__python3}
export PYTHON_VERSION=3
export PYTHON_VERSIONS=python3

pushd libraries/libapparmor
./autogen.sh
%configure \
    --with-python
popd

%build

pushd libraries/libapparmor
%make_build VERSION=%normver
popd

%make_build -C binutils
%make_build -C parser
%make_build -C profiles
%make_build -C utils
%make_build -C changehat/pam_apparmor
%make_build -C changehat/mod_apparmor
%make_build -C utils/vim

%install
mkdir -p %buildroot%_datadir/polkit-1/actions/
%make_install -C libraries/libapparmor
%make_install -C binutils
%make_install -C parser \
    APPARMOR_BIN_PREFIX=%{buildroot}%{_prefix}/lib/apparmor \
    SBINDIR=%{buildroot}%{_sbindir}

# Enable parser cache writing/compression by default so profile loads at
# boot (rc.apparmor.functions parses 1500+ profiles) don't re-parse from
# source every time, and point the cache at a dedicated /var/cache/apparmor
# instead of the default /etc/apparmor.d/cache (read-only image /etc).
sed -i \
    -e 's/^#write-cache$/write-cache/' \
    -e 's/^#Optimize=compress-fast$/Optimize=compress-fast/' \
    %{buildroot}%{_sysconfdir}/apparmor/parser.conf
echo 'cache-loc /var/cache/apparmor' >> %{buildroot}%{_sysconfdir}/apparmor/parser.conf
install -dm755 %{buildroot}%{_localstatedir}/cache/apparmor

# init/ installs aa-teardown, apparmor.service, and the rc.apparmor.functions
# helpers into APPARMOR_BIN_PREFIX - none of this is covered by the parser
# install above (their Makefiles are separate), so the parser package's
# aa-teardown/apparmor.service/%{_prefix}/lib/apparmor entries need it.
# Without this, nothing ever loads profiles into the kernel at boot - the
# LSM comes up with zero profiles, and anything execing with
# AppArmorProfile= (e.g. dbus-broker's systemd drop-in) fails outright
# because the profile it expects was never loaded.
%make_install -C init \
    DISTRO=redhat \
    APPARMOR_BIN_PREFIX=%{buildroot}%{_prefix}/lib/apparmor \
    SBINDIR=%{buildroot}%{_sbindir} \
    USR_SBINDIR=%{buildroot}%{_sbindir} \
    SYSTEMD_UNIT_DIR=%{buildroot}%{_unitdir}
%make_install -C profiles
%make_install -C utils
%make_install -C changehat/pam_apparmor \
    SECDIR=%{buildroot}%{_libdir}/security
%make_install -C changehat/mod_apparmor
%make_install -C utils/vim

install -Dm644 %{SOURCE1} %{buildroot}%{_presetdir}/70-apparmor.preset

find %{buildroot} \( -name "*.a" -o -name "*.la" \) -delete

mkdir -p %buildroot%python3_sitearch/LibAppArmor
mv %buildroot%python3_sitearch/{LibAppArmor.py,_LibAppArmor.cpython-*-linux-gnu.so,__pycache__/LibAppArmor.*} %buildroot%python3_sitearch/LibAppArmor/
# Without this, the moved-into-a-subdir LibAppArmor.py is never executed on
# `import LibAppArmor` - Python just treats the directory as an empty
# implicit namespace package, so callers (e.g. apparmor-utils'
# logparser.py, which does `import LibAppArmor` then
# `LibAppArmor.parse_record(...)`) get "module 'LibAppArmor' has no
# attribute 'parse_record'" even though the real SWIG bindings are right
# there on disk.
echo 'from .LibAppArmor import *' > %buildroot%python3_sitearch/LibAppArmor/__init__.py

%find_lang aa-binutils
%find_lang apparmor-parser
%find_lang apparmor-utils


%if %{with tests}
%check
make -C libraries/libapparmor check
make -C binutils check
make -C parser check
# only running check-parser, as check-logprof (included in check) fails:
# https://gitlab.com/apparmor/apparmor/issues/36
make -C profiles check-parser
make -C profiles check
# shutil.copytree has a regression
# https://gitlab.com/apparmor/apparmor/issues/62
make -C utils check
%endif

%post parser
%systemd_post %{name}.service

%preun parser
%systemd_preun %{name}.service

%postun parser
%systemd_postun_with_restart %{name}.service

%files libs
%license LICENSE
%{_libdir}/libapparmor.so.*

%files devel
%{_libdir}/libapparmor.so
%{_includedir}/aalogparse
%{_includedir}/sys/apparmor*
%{_libdir}/pkgconfig/libapparmor.pc
%{_mandir}/man2/aa_*.2.gz
%{_mandir}/man3/aa_*.3.gz

%files -n python3-apparmor
%doc README.md
%{python3_sitelib}/apparmor
%{python3_sitelib}/apparmor-*.egg-info

%files -n python3-LibAppArmor
%doc README.md
%{python3_sitearch}/LibAppArmor
%{python3_sitearch}/LibAppArmor-*.egg-info

%files profiles
%dir %{_sysconfdir}/apparmor.d/
# Everything under apparmor.d/ (the flat sample profiles, abi/,
# abstractions/, local/, tunables/, apache2.d/) is claimed recursively by
# this single glob instead of being enumerated by name - upstream adds and
# removes bundled sample profiles between releases (5.0.2 ships ~150 of
# them, not the dozen this list used to hardcode), and an enumerated list
# silently drifts out of sync, leaving newly-added files unpackaged and
# build failing with "Installed (but unpackaged) file(s) found".
%config(noreplace) %{_sysconfdir}/apparmor.d/*
%dir %{_datadir}/apparmor/
%{_datadir}/apparmor/extra-profiles

%files parser -f apparmor-parser.lang -f aa-binutils.lang
%license parser/COPYING.GPL
%doc parser/README
%doc parser/*.[1-9].html
%doc common/apparmor.css
%{_sbindir}/apparmor_parser
%{_bindir}/aa-enabled
%{_bindir}/aa-exec
%{_bindir}/aa-features-abi
%{_sbindir}/aa-load
%{_sbindir}/aa-show-usage
%{_sbindir}/aa-teardown
%{_unitdir}/apparmor.service
%{_presetdir}/70-apparmor.preset
%{_prefix}/lib/apparmor
%dir %{_sysconfdir}/apparmor
%config(noreplace) %{_sysconfdir}/apparmor/default_unconfined.template
%config(noreplace) %{_sysconfdir}/apparmor/parser.conf
%dir %{_localstatedir}/cache/apparmor
%{_mandir}/man1/aa-enabled.1.gz
%{_mandir}/man1/aa-exec.1.gz
%{_mandir}/man1/aa-features-abi.1.gz
%{_mandir}/man5/apparmor.d.5.gz
%{_mandir}/man5/apparmor.vim.5.gz
%{_mandir}/man7/apparmor.7.gz
%{_mandir}/man7/apparmor_xattrs.7.gz
%{_mandir}/man8/aa-load.8.gz
%{_mandir}/man8/aa-show-usage.8.gz
%{_mandir}/man8/aa-teardown.8.gz
%{_mandir}/man8/apparmor_parser.8.gz

%files utils -f apparmor-utils.lang
%doc utils/*.[0-9].html
%doc utils/vim/apparmor.vim.5.html
%doc common/apparmor.css
%dir %{_sysconfdir}/apparmor
%config(noreplace) %{_sysconfdir}/apparmor/easyprof.conf
%config(noreplace) %{_sysconfdir}/apparmor/logprof.conf
%config(noreplace) %{_sysconfdir}/apparmor/notify.conf
%config(noreplace) %{_sysconfdir}/apparmor/severity.db
%{_bindir}/aa-easyprof
%{_sbindir}/aa-audit
%{_sbindir}/aa-autodep
%{_sbindir}/aa-cleanprof
%{_sbindir}/aa-complain
%{_sbindir}/aa-decode
%{_sbindir}/aa-disable
%{_sbindir}/aa-enforce
%{_sbindir}/aa-genprof
%{_sbindir}/aa-logprof
%{_sbindir}/aa-mergeprof
%{_sbindir}/aa-notify
%{_sbindir}/aa-remove-unknown
%{_sbindir}/aa-status
%{_sbindir}/aa-unconfined
%{_sbindir}/apparmor_status
%dir %{_datadir}/apparmor
%{_datadir}/apparmor/easyprof
%{_datadir}/apparmor/apparmor.vim
%{_datadir}/polkit-1/actions/net.apparmor.pkexec.aa-notify.policy
%{_mandir}/man5/logprof.conf.5.gz
%{_mandir}/man8/aa-audit.8.gz
%{_mandir}/man8/aa-autodep.8.gz
%{_mandir}/man8/aa-cleanprof.8.gz
%{_mandir}/man8/aa-complain.8.gz
%{_mandir}/man8/aa-decode.8.gz
%{_mandir}/man8/aa-disable.8.gz
%{_mandir}/man8/aa-easyprof.8.gz
%{_mandir}/man8/aa-enforce.8.gz
%{_mandir}/man8/aa-genprof.8.gz
%{_mandir}/man8/aa-logprof.8.gz
%{_mandir}/man8/aa-mergeprof.8.gz
%{_mandir}/man8/aa-notify.8.gz
%{_mandir}/man8/aa-remove-unknown.8.gz
%{_mandir}/man8/aa-status.8.gz
%{_mandir}/man8/aa-unconfined.8.gz
%{_mandir}/man8/apparmor_status.8.gz

%files -n pam_apparmor
%doc README.md
%{_libdir}/security/pam_apparmor.so

%files -n mod_apparmor
%{_libdir}/httpd/modules/mod_apparmor.so
%{_mandir}/man8/mod_apparmor.8.gz

%changelog
* Fri Aug 07 2026 CatPieLeaf <catpieleaf@proton.me> - 5.0.2-2
- Package the apparmor.service systemd unit (init/ was never built, so
  nothing ever loaded profiles into the kernel at boot); fix a %files
  parser/profiles file-conflict landmine; replace the stale enumerated
  %files profiles list with a recursive glob so it can't drift out of
  sync with upstream again; enable parser cache write/compression;
  fix LibAppArmor's __init__.py; utils Requires apparmor-parser and
  Obsoletes setroubleshoot; two more upstream sample-profile patches
  (dnsmasq nsswitch, waydroid).
- Patch SWIG's removed %new_copy_array macro (swig 4.5.0+ breaks the
  python bindings build otherwise).
- Fix two EL10/CentOS Stream 10 CI parse failures shared with
  apparmor-libs32.spec: a debuginfo Name collision (now scoped to
  rhel builds only, per review - Fedora keeps normal debuginfo) and
  RPM macro-expanding install/files section tokens inside comments.
- Use the proper SPDX GPL-2.0-only identifier instead of bare GPL-2.0.

* Sat Aug 08 2026 CatPieLeaf <catpieleaf@proton.me> - 5.0.2-3
- Hotfix: Removed "Obsoletes: setroubleshoot"

%autochangelog
