# Generated by go2rpm 1.15.0

# https://github.com/jesseduffield/lazygit
%global goipath         github.com/jesseduffield/lazygit
Version:                0.59.0

%gometa -f

%global common_description %{expand:
Simple terminal UI for git commands.}

%global golicenses      LICENSE
%global godocs          docs README.md VISION.md

Name:           golang-github-jesseduffield-lazygit
Release:        2%?dist
Summary:        Simple terminal UI for git commands

License:        MIT
URL:            %{gourl}
Source:         %{gosource}
Packager:       sadlerm <lerm@chromebooks.lol>

BuildRequires:  anda-srpm-macros

Provides:       lazygit = %{evr}

%description %{common_description}


%package        doc
Summary:        Documentations for %{name}
Requires:       %{name} = %{evr}
BuildArch:      noarch

%description    doc
%{summary}.

%gopkg

%prep
%goprep -A

%build
%define currentgoldflags -X main.version=%version
%define gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/lazygit %{goipath}

%install
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%files
%license LICENSE
%doc README.md
%{_bindir}/lazygit

%files doc
%doc docs/ VISION.md CONTRIBUTING.md CODE-OF-CONDUCT.md
