# Generated by go2rpm 1.15.0

# https://github.com/jesseduffield/lazygit
%global goipath         github.com/jesseduffield/lazygit
Version:                0.58.1

%gometa -f

%global common_description %{expand:
Simple terminal UI for git commands.}

%global golicenses      LICENSE
%global godocs          docs README.md VISION.md

Name:           golang-github-jesseduffield-lazygit
Release:        1%?dist
Summary:        Simple terminal UI for git commands

License:        MIT
URL:            %{gourl}
Source:         %{gosource}
Packager:       sadlerm <lerm@chromebooks.lol>

BuildRequires:  anda-srpm-macros

Provides:       lazygit = %{version}-%{release}

%description %{common_description}

%gopkg

%prep
%goprep -A

%build
%define currentgoldflags -X main.version=%version
%define gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/lazygit %{goipath}

%install
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%files
%license LICENSE
%doc docs README.md VISION.md
%{_bindir}/lazygit
