# generated by cabal-rpm-2.3.2
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global pkg_name midi
%global pkgver %{pkg_name}-%{version}
%{?haskell_setup}

# testsuite missing deps: event-list explicit-exception non-negative utility-ht

Name:           ghc-%{pkg_name}
Version:        0.2.2.6
Release:        1%{?dist}
Summary:        Handling of MIDI messages and files

License:        LicenseRef-GPL
URL:            https://hackage.haskell.org/package/midi
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-event-list-devel
BuildRequires:  ghc-explicit-exception-devel
BuildRequires:  ghc-monoid-transformer-devel
BuildRequires:  ghc-non-negative-devel
BuildRequires:  ghc-random-devel
BuildRequires:  ghc-semigroups-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-utility-ht-devel
%if %{with ghc_prof}
BuildRequires:  ghc-QuickCheck-prof
BuildRequires:  ghc-base-prof
BuildRequires:  ghc-binary-prof
BuildRequires:  ghc-bytestring-prof
BuildRequires:  ghc-event-list-prof
BuildRequires:  ghc-explicit-exception-prof
BuildRequires:  ghc-monoid-transformer-prof
BuildRequires:  ghc-non-negative-prof
BuildRequires:  ghc-random-prof
BuildRequires:  ghc-semigroups-prof
BuildRequires:  ghc-transformers-prof
BuildRequires:  ghc-utility-ht-prof
%endif
# End cabal-rpm deps

Packager:       Owen Zimmerman <owen@fyralabs.com>

%description
MIDI is the Musical Instrument Digital Interface. The package contains
definition of realtime and file MIDI messages, reading and writing MIDI files,
and some definitions from the General MIDI standard. It contains no sending and
receiving of MIDI messages. For this purpose see the 'alsa-seq', 'jack',
'PortMidi', 'hmidi' packages. For music composition with MIDI output, see
'haskore'. Alternative packages are 'HCodecs', 'zmidi-core'.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-static%{?_isa} = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%if %{with haddock}
%package doc
Summary:        Haskell %{pkg_name} library documentation
BuildArch:      noarch
Requires:       ghc-filesystem

%description doc
This package provides the Haskell %{pkg_name} library documentation.
%endif


%if %{with ghc_prof}
%package prof
Summary:        Haskell %{pkg_name} profiling library
Requires:       %{name}-devel%{?_isa} = %{version}-%{release}
Supplements:    (%{name}-devel and ghc-prof)

%description prof
This package provides the Haskell %{pkg_name} profiling library.
%endif


%prep
# Begin cabal-rpm setup:
%setup -q -n %{pkgver}
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%ghc_lib_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_lib_install
# End cabal-rpm install


%files -f %{name}.files
# Begin cabal-rpm files:
%license LICENSE
# End cabal-rpm files


%files devel -f %{name}-devel.files


%if %{with haddock}
%files doc -f %{name}-doc.files
%license LICENSE
%endif


%if %{with ghc_prof}
%files prof -f %{name}-prof.files
%endif


%changelog
* Fri Jul 10 2026 Owen-sz <owen@fyralabs.com> - 0.2.2.6-1
- spec file generated by cabal-rpm-2.3.2
