PACKAGE_NAME="hid-tmff2"
PACKAGE_VERSION="__VERSION_STRING"
AUTOINSTALL="yes"

MAKE[0]="'make' KDIR=\"$kernel_source_dir\""
CLEAN[0]=true

BUILT_MODULE_LOCATION[0]="deps/hid-tminit/"
BUILT_MODULE_NAME[0]="hid-tminit"
DEST_MODULE_LOCATION[0]="/extra"

BUILT_MODULE_NAME[1]="hid-tmff-new"
DEST_MODULE_LOCATION[1]="/extra"
