PACKAGE_NAME="hid-tmff2"
PACKAGE_VERSION="__VERSION_STRING"
AUTOINSTALL="yes"

MAKE[0]="'make' KDIR=\"$kernel_source_dir\""
CLEAN[0]=true

BUILT_MODULE_NAME[0]="hid-tmff-new"
DEST_MODULE_LOCATION[0]="/extra"
