%global ver v1.14.1

# Generated by go2rpm 1.19.0
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$

# https://github.com/SagerNet/sing-box
%global goipath         github.com/SagerNet/sing-box
Version:                %(echo %ver | sed 's/-/./g;s/v//')

%gometa -f

%global ref %ver

%global common_description %{expand:
The universal proxy platform.}

%global golicenses      LICENSE common/ja3/LICENSE\\\
                        common/windivert/assets/LICENSE.txt
%global godocs          docs README.md common/ja3/README.md\\\
                        common/tlsspoof/README.md transport/simple-\\\
                        obfs/README.md

Name:           sing-box
Release:        2%?dist
Summary:        The universal proxy platform

License:        BSD-3-Clause AND LGPL-3.0-only AND GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}
Packager:       madonuko <mado@fyralabs.com>

%description %{common_description}

%gopkg

%prep
%autosetup -n %name-%(echo %ver | sed 's/v//')
%goprep -Ae
%autopatch -p1

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/sing-box ./cmd/sing-box

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dm644 release/config/sing-box.service %{buildroot}%{_unitdir}/sing-box.service
install -Dm644 release/config/sing-box@.service %{buildroot}%{_unitdir}/sing-box@.service
install -Dm644 release/config/sing-box.confd    %{buildroot}%{_sysusersdir}/sing-box.confd

%post
%systemd_post sing-box.service sing-box@.service

%preun
%systemd_preun sing-box.service sing-box@.service

%postun
%systemd_postun_with_restart sing-box.service sing-box@.service

%files
%license LICENSE common/ja3/LICENSE common/windivert/assets/LICENSE.txt
%doc docs README.md common/ja3/README.md common/tlsspoof/README.md
%doc transport/simple-obfs/README.md
%{_bindir}/sing-box
%{_unitdir}/sing-box.service
%{_unitdir}/sing-box@.service
%{_sysusersdir}/sing-box.confd

%gopkgfiles
