%global ver v1.13.19

# Generated by go2rpm 1.19.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/SagerNet/sing-box
%global goipath         github.com/SagerNet/sing-box
Version:                %(echo %ver | sed 's/-/./g;s/v//')

%gometa -f

%global ref %ver

%global common_description %{expand:
The universal proxy platform.}

%global golicenses      LICENSE common/ja3/LICENSE\\\
                        common/windivert/assets/LICENSE.txt
%global godocs          docs README.md common/ja3/README.md\\\
                        common/tlsspoof/README.md transport/simple-\\\
                        obfs/README.md

Name:           sing-box
Release:        1%?dist
Summary:        The universal proxy platform

License:        BSD-3-Clause AND LGPL-3.0-only AND GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}
Packager:       madonuko <mado@fyralabs.com>

%description %{common_description}

%gopkg

%prep
%autosetup -n %name-%(echo %ver | sed 's/v//')
%goprep -Ae
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/sing-box ./cmd/sing-box
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE common/ja3/LICENSE common/windivert/assets/LICENSE.txt
%doc docs README.md common/ja3/README.md common/tlsspoof/README.md
%doc transport/simple-obfs/README.md
%{_bindir}/sing-box
%endif

%gopkgfiles
