# for each folder in anda/
# generate a new workflow for each folder in anda/
name: Automatically build packages
permissions:
  contents: read
on:
  # push:
  #   paths:
  #     - anda/**
  #   branches:
  #     - frawhide
  pull_request:
    paths:
      - anda/**
    branches:
      - frawhide
  merge_group:
    paths:
      - anda/**
    branches:
      - frawhide
  workflow_dispatch:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-24.04-arm
    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
    container:
      image: ghcr.io/terrapkg/builder:frawhide
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Set workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate build matrix
        id: generate_build_matrix
        run: anda ci >> $GITHUB_OUTPUT
  build:
    needs: manifest
    uses: ./.github/workflows/json-build.yml
    secrets: inherit
    with:
      packages: ${{ needs.manifest.outputs.build_matrix }}
      publish: ${{ github.event_name == 'push' }}

  automerge:
    needs: build
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Merge PR on Success Build
        if: github.event.pull_request.commits == 1 && github.event.pull_request.user.login == 'raboneko'
        run: gh pr merge ${{ github.event.number }} --admin --squash

  appstream:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/appstream-generator:main
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: ./artifacts
      - name: Generate test catalog
        # run appstream-builder, then add step summary
        run: |
          set -x
          appstream-builder -v \
            --packages-dir=artifacts/rpms \
            --icons-dir=icons \
            --include-failed \
            --output-dir=output \
            --uncompressed-icons \
            --origin=test \
            --basename=test \
            --veto-ignore=missing-parents \
            --veto-ignore=missing-info 2>&1 | tee asb.log
      - name: Export logs
        id: export_logs
        run: |
          echo "## AppStream Builder Log" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```log' >> $GITHUB_STEP_SUMMARY
          cat asb.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY

      - name: Report Summary
        id: report_summary
        run: |
          echo "## AppStream Builder Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if grep -q "veto" asb.log; then
            echo "::group::Vetoed packages"
            echo "### Vetoed packages" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```xml' >> $GITHUB_STEP_SUMMARY
            echo "$(grep -i 'veto' asb.log)" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "::warning file=asb.log::Some packages were vetoed during AppStream generation. Please review the 'Vetoed packages' section in the summary for details."
            echo "::endgroup::"
          fi
          echo "## Full Data Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Generated Appstream files:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for file in output/*.xml.gz; do
            echo "#### \`$file\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```xml' >> $GITHUB_STEP_SUMMARY
            zcat "$file" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          done

  lintUpdate:
    needs: manifest
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      pull-requests: write
    container:
      image: ghcr.io/terrapkg/builder:frawhide
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}

      - name: Install SSH signing key & Set up git repository
        run: |
          mkdir -p ${{ runner.temp }}
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ${{ runner.temp }}/signing_key
          chmod 0700 ${{ runner.temp }}/signing_key
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Collect update scripts from last commit
        id: last_commit_update_scripts
        run: |
          scripts=$(git diff-tree --no-commit-id --name-only HEAD -r | grep -E '/update\.rhai$' || true)
          scripts=$(printf "%s" "$scripts" | tr '\n' ' ')
          echo "upd_scripts=${scripts}" >> $GITHUB_OUTPUT

      - name: Run update scripts from last commit
        if: steps.last_commit_update_scripts.outputs.upd_scripts != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          pr_number="${{ github.event.pull_request.number }}"
          for script in ${{ steps.last_commit_update_scripts.outputs.upd_scripts }}; do
            echo "Running update script: $script"
            dir=$(dirname "$script")
            hcl="$dir/anda.hcl"
            if [ ! -f "$hcl" ]; then
              echo "Missing anda.hcl for $script"
              continue
            fi

            backup="$hcl.autobuild_upd_test.bak"
            cp $hcl $backup
            if ! grep -qE 'labels {' $hcl; then
              sed -E '/rpm\s*{/i labels { autobuild_upd_test = 1 }' -i $hcl
            else
              sed -E '/labels\s*{/a autobuild_upd_test = 1' -i $hcl
            fi

            output=$(anda run "$script" -f autobuild_upd_test=1 2>&1) || status=$?
            status=${status:-0}
            echo "$output"

            mv "$backup" "$hcl" # do we want to commit this too?

            if echo "$output" | grep -q "ERROR" || [ "$status" -ne 0 ]; then
              gh pr comment ${{ github.event.pull_request.number }} --body "Update script failed: $script\n\n\`\`\`\n$output\n\`\`\`"
              exit 1
            fi
          done
