name: Update
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/terrapkg/builder:frawhide
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}

      - name: Install SSH signing key & Set up git repository
        run: |
          mkdir -p ${{ runner.temp }}
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ${{ runner.temp }}/signing_key
          chmod 0700 ${{ runner.temp }}/signing_key
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run Update
        run: anda update -e nightly=1 -e updbranch=1 -e weekly=0 -e weekly=1 -e weekly=2 -e weekly=3 -e weekly=4 -e weekly=5 -e weekly=6
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOUPDATE_GH_TOKEN }}
          RUST_BACKTRACE: full

      - name: Save
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "Raboneko"
            git config user.email "raboneko@fyralabs.com"
            git config gpg.format "ssh"
            git config user.signingkey "${{ runner.temp }}/signing_key"
            anda run andax/ci/update_pr.rhai -l scope=auto
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
